#!/bin/sh
city="put your city here"
while :
do
	weather_raw=$(ansiweather -l $city -u metric -s true)
	temp=$(echo "$weather_raw" | grep -oP '\d+(?= °C)')
	wind=$(echo "$weather_raw" | grep -oP '\d+(\.\d+)?(?= m/s)')
	humidity=$(echo "$weather_raw" | grep -oP '\d+(?=%)')
	path=/tmp/weatherzshresult.txt
	printf '\uf2c8 %s°c \uef16 %sm/s \uf043 %s%%\n' "$temp" "$wind" "$humidity" > $path
	sleep 60
done
